# Generated by Django 6.0.5 on 2026-05-29 22:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caso_id', models.CharField(max_length=200, unique=True)),
                ('email_remitente', models.CharField(max_length=500)),
                ('email_asunto', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], default='RECIBIDA', max_length=20)),
                ('recibida_en', models.DateTimeField(auto_now_add=True)),
                ('procesada_en', models.DateTimeField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-recibida_en'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('formato', models.CharField(max_length=50)),
                ('contenido_texto', models.TextField(blank=True)),
                ('tipo_doc', models.CharField(blank=True, max_length=50)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.CharField(choices=[('A', 'Clasificación'), ('B', 'Extracción'), ('C', 'Dictamen')], max_length=1)),
                ('resultado', models.JSONField()),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.carpeta')),
            ],
            options={
                'ordering': ['paso'],
                'unique_together': {('carpeta', 'paso')},
            },
        ),
    ]
